### ISSUE TITLE
libgnome-keyring will be removed

### ISSUE THREAD

**Issue by huseyinkozan** [msva/mva-overlay#144]
Hi,

I am trying to install Atom editor. After `layman` gives an error about masked `libgnome-keyring` checked at [packages](https://packages.gentoo.org/packages/gnome-base/libgnome-keyring), it says `This package is masked and could be removed soon!`.
Should I continue unmask it and use, or can I use an alternative for it ?

**Comment by msva** [comment]
Unfortunatelly, the way how portage works leads to the fact that any package 
masking in gentoo repo also mask that package in all the overlays.

So, you can either unmask it, or wait for it to be removed from gentoo repo 
(mask should be also dropped), or even better move it to the local overlay and 
unmask it from there (since I can drop it from overlay in near future too).






В письме от воскресенье, 6 декабря 2020 г. 21:56:36 +07 пользователь Hüseyin 
Kozan написал:
> Hi,
> 
> I am trying to install Atom editor. After `layman` gives an error about
> masked `libgnome-keyring` checked at
> [packages](https://packages.gentoo.org/packages/gnome-base/libgnome-keyring
> ), it says `This package is masked and could be removed soon!`. Should I
> continue unmask it and use, or can I use an alternative for it ?
