### ISSUE TITLE
Possible overlook in net-im/telegram-desktop ebuild

### ISSUE THREAD

**Issue by zendet** [msva/mva-overlay#173]
If I try to build `net-im/telegram-desktop` without `webrtc` USE-flag i get an "By not providing "Findtg_owt.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "tg_owt", but CMake did not find one." error. I think it happening because disabling the `webrtc` USE-flag entails ignoring of the installing a `tg_owt` package.

**Comment by msva** [comment]
1) yes, the reason is exactly in the flag.

2) Please, note: https://github.com/msva/mva-overlay/blob/master/net-im/telegram-desktop/telegram-desktop-4.7.1.ebuild#L168-L172

TL;DR: upstream made webrtc mandatory, and for now build fails without it.
It is possible that someday I'll made a patch to made it optional, but for now I have not enough spare time, so no guaranties on ETA (and will it be at all).

And that message must be appeared when you tried to build telegram without webrtc :man_shrugging:
