### ISSUE TITLE
Passenger NginX module destiny

### ISSUE THREAD

**Issue by msva** [msva/mva-overlay#51]
Unfortunately, I'm very disappointed by Passenger's development workflow, so I deciding to remove it from the nginx ebuild. If somebody want to discuss it — here is the place.

**Comment by infoman** [comment]
Seems that it's already broken again, saying: ```unknown directive "passener_root" in /etc/nginx/nginx.conf:48```.

So, no one except me is using it?

**Comment by msva** [comment]
@infoman strange. I'm (still) using it on production and it works for me. But, anyway, looking in their issue list, where bugs (with patches attached!) are opened for 8 years (!!!), and where they "moving" milestone on very popular (!!!) feature request about per-application logs... So... I think, it will be better to quote NginX developers, that passenger is a piece of... uhm... <strange thing>.

// Although, not that uwsgi would be better. So, it'll be probably (g)unicorn/thin...

// Anyway, for now, I'll not remove it from the ebuild. Until they brake something else, that passenger will refuse to build again.

// and, talking on your issue — I'll try to investigate it a bit more and maybe ask some questions.

**Comment by infoman** [comment]
Sorry, about that error in original comment — it was just my typo in directive name and I already fixed it.

About some other application server — the problem is that for multiple applications I must run and configur a server instance for each app, that could be boring sometimes, and Passenger has all configuration in one place, that is just simpler to maintain. Also there's no headache to start all these servers when the machine goes up, the Passenger daemon starts all applications automatically at first request and can even shut them down if no one used them for an amount of time.

Some of this functionality can possibly be achieved by writing some unicorn@.service systemd units and using socket activation, but this will be even more configuration headache, that can be just avoided with Passenger.

The build system is not that good as the other parts unfortunately :(
