### ISSUE TITLE
www-servers/nginx: 'http2' USE flag, like it's done in Gentoo's overlay

### ISSUE THREAD

**Issue by stefantalpalaru** [msva/mva-overlay#53]
The current "v2" appearing in NGINX_MODULES_HTTP is unclear, undocumented, and might become a nasty surprise for somebody who already has 'http2' enabled and adds your overlay.

**Comment by msva** [comment]
talking about "undocumented" — my bad, but I just have not enough time to properly maintain metadata.
Talking about "unclear" and "might be a surprise" — 
1) It absolutelly corresponds `econf` parameters generation scheme (in for-loop), since upstream exactly enables/disables it as http-module named "v2".
2) To doesn't brake loop with kludges, I suggest addition "http2" useflag as "REQUIRED_USE=http2? ( nginx_modules_http_v2 )"
3) actually, I've introduced "v2" in NGINX_MODULES_HTTP so long time ago, when there wasn't even thoughts about http2 in gentoo nginx ebuild maintainer's head.
By the way, since it is he (gentoo maintainer), who taking ebuild from my overlay and change it in some strange way (I disagree with), I don't understand why should **I** adjust to it, but not vice versa.

Anyway, thanks for opinion, I'll do something in that way on next bump (or on PR).
