### ISSUE TITLE
Passenger module in nginx is not working with ruby23

### ISSUE THREAD

**Issue by andrew-aladev** [msva/mva-overlay#85]
I am trying to use passenger module with ruby23 and it looks like it is broken.

While using `passenger_root /usr/libexec/passenger`:

```
/usr/bin/ruby23: No such file or directory -- /usr/libexec/passenger/src/helper-scripts/rack-preloader.rb (LoadError)
```

I couldn't see an `src` folder in /usr/libexec/passenger. So I've tried to create a symlink `/usr/libexec/passenger/src -> /usr/libexec/passenger`.

```
Message from application: cannot load such file -- /usr/libexec/passenger/src/ruby_supportlib/phusion_passenger (LoadError)
  /usr/lib64/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib64/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/libexec/passenger/src/helper-scripts/rack-preloader.rb:74:in `init_passenger'
```

So `options["ruby_libdir"]` equals `/usr/libexec/passenger/src/ruby_supportlib`. But in `/usr/libexec/passenger/locations.ini` `ruby_libdir` equals `/usr/lib64/ruby/2.3.0/x86_64-linux`.

What is going on?

**Comment by andrew-aladev** [comment]
I can create a symlink `/usr/libexec/passenger/src -> /usr/local/lib64/ruby/gems/2.3.0/gems/passenger-5.1.1/src` and passenger will work fine. But this is not a solution.

**Comment by msva** [comment]
Either you did not read the message in `postinst`, or I badly described what should be done.

`passenger_root` should point not on the directory, where `locations.ini` placed, but on the file itself.
I.e. file should be in the path (`/usr/libexec/passenger/locations.ini`).

... And it is an upstream issue. They prefer to do many things "per rectum".

That's why some time ago I decided to drop passenger from nginx ebuild someday (but some users asked to not do that, and I not sure, if I regret of still keeping it here or not).

**Comment by andrew-aladev** [comment]
Aaa, thank you.
