### ISSUE TITLE
[FR] app-backup/duplicati-2.*

### ISSUE THREAD

**Issue by skobkin** [msva/mva-overlay#98]
It would be nice if recent version of `app-backup/duplicati` was in this overlay.

I think the base for ebuild could be taken from [this Gentoo Bugzilla](https://bugs.gentoo.org/show_bug.cgi?id=522374) ticket.

![Cat with big eyes](https://i.skobk.in/i/cats/256/cat_eyes.png)

**Comment by msva** [comment]
As noted in the bug on bz, you can install both of them from https://github.com/fritteli/gentoo-overlay/ (v2 ebuild is "duplicati-bin")

I doubt, I can do something more than just copy the ebuild here (and, since I've no practical use-case of that software, I can't guarantee that I'll maintain it properly)...

**Comment by skobkin** [comment]
Last time I checked friteli's overlay ebuild didn't work at all.
